# Generated by Django 5.2.1 on 2025-05-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(choices=[('lumley', 'Lumley'), ('regent_road', 'Regent Road'), ('aberdeen', 'Aberdeen'), ('hill_station', 'Hill Station'), ('kissy', 'Kissy'), ('east_end', 'East End'), ('wilberforce', 'Wilberforce'), ('tower_hill', 'Tower Hill'), ('ferry_junction', 'Ferry Junction'), ('goderich', 'Goderich'), ('kent', 'Kent'), ('congo_cross', 'Congo Cross')], max_length=50)),
                ('destination', models.CharField(choices=[('lumley', 'Lumley'), ('regent_road', 'Regent Road'), ('aberdeen', 'Aberdeen'), ('hill_station', 'Hill Station'), ('kissy', 'Kissy'), ('east_end', 'East End'), ('wilberforce', 'Wilberforce'), ('tower_hill', 'Tower Hill'), ('ferry_junction', 'Ferry Junction'), ('goderich', 'Goderich'), ('kent', 'Kent'), ('congo_cross', 'Congo Cross')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('origin', 'destination', 'departure_time')},
            },
        ),
    ]
