# Generated by Django 5.2.1 on 2025-05-31 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('terminals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination_terminal',
            field=models.ForeignKey(blank=True, help_text='Terminal where this route ends', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_routes', to='terminals.terminal'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_terminal',
            field=models.ForeignKey(blank=True, help_text='Terminal where this route starts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_routes', to='terminals.terminal'),
        ),
    ]
