# Generated by Django 5.2.1 on 2025-05-31 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('terminal_type', models.CharField(choices=[('main_terminal', 'Main Terminal'), ('bus_stop', 'Bus Stop'), ('interchange', 'Interchange'), ('depot', 'Bus Depot')], max_length=20)),
                ('location', models.CharField(help_text='Street address or landmark', max_length=100)),
                ('city', models.CharField(choices=[('freetown', 'Freetown'), ('bo', 'Bo'), ('kenema', 'Kenema'), ('makeni', 'Makeni'), ('koidu', 'Koidu')], default='freetown', max_length=50)),
                ('coordinates_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('coordinates_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional information about the terminal')),
                ('facilities', models.TextField(blank=True, help_text='Available facilities (comma-separated)')),
                ('operating_hours_start', models.TimeField(help_text='Terminal opening time')),
                ('operating_hours_end', models.TimeField(help_text='Terminal closing time')),
                ('contact_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city', 'terminal_type'], name='terminals_t_city_88ff8e_idx'), models.Index(fields=['is_active'], name='terminals_t_is_acti_64b886_idx')],
            },
        ),
    ]
