# Generated by Django 5.2.1 on 2025-06-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mobile_money_number',
            field=models.CharField(blank=True, help_text='Phone number for mobile money payments', max_length=15, null=True),
        ),
    ]
