# Generated by Django 5.2.1 on 2025-06-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_mobile_money_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='card_cvc',
            field=models.CharField(blank=True, help_text='Card security code', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='card_expiry',
            field=models.CharField(blank=True, help_text='Card expiry date (MM/YY)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='card_number',
            field=models.CharField(blank=True, help_text='Card number for PayPal payments', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='card_owner_name',
            field=models.CharField(blank=True, help_text="Cardholder's full name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateTimeField(blank=True, help_text='Required for round trip bookings', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20),
        ),
    ]
