# Generated by Django 5.2.1 on 2025-07-13 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_card_cvc_booking_card_expiry_and_more'),
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_bus',
            field=models.ForeignKey(blank=True, help_text='Bus for return journey (round trips only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_bookings', to='buses.bus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_seat',
            field=models.ForeignKey(blank=True, help_text='Seat for return journey (round trips only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_bookings', to='buses.seat'),
        ),
    ]
